name: Update LeetCode Statistics

on:
  push:
    branches: [ main ]
    # Only run when files in the LeetCode solutions directory change
    paths:
      - 'leetcode/**'        # Adjust this path to match your LeetCode solutions directory
      - 'solutions/**'       # Add additional paths if needed
  workflow_dispatch:         # Keep manual trigger option

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Generate LeetCode statistics and update README
        run: python stats_viz.py
      
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add leetcode_stats.svg README.md
          if ! git diff --cached --quiet; then
            git commit -m "Update LeetCode statistics"
            git push
          else
            echo "No changes to commit."
          fi
